language: c
os:
  - linux
compiler:
  - clang
  - gcc
env:
  global:
    - MAKEFLAGS="-j 2"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq -y libaio-dev libnuma-dev libz-dev; fi
